<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            [
                'name'         => 'Kampung Heritage Kayutangan',
                'category'     => 'Wisata Budaya',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => '3 km',
                'rating'       => 4.9,
                'review_count' => 100,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Basuki Rahmat, Kauman, Klojen, Kota Malang',
                'description'  => 'Kawasan wisata budaya bersejarah dengan bangunan kolonial Belanda yang terawat. Cocok untuk wisata sejarah dan fotografi.',
                'emoji'        => '🏛️',
                'color'        => '#8b7355',
                'gradient'     => 'linear-gradient(135deg,#8b7355,#6b5233)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Trunojoyo Park',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => '1 km',
                'rating'       => 4.9,
                'review_count' => 80,
                'ticket_price' => 'Gratis',
                'open_hours'   => '06.00–21.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Trunojoyo, Klojen, Kota Malang',
                'description'  => 'Taman kota yang asri di pusat Kota Malang. Tempat favorit warga untuk jogging dan bersantai.',
                'emoji'        => '🌳',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#1e8449)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Warna-Warni Jodipan',
                'category'     => 'Wisata Edukasi',
                'location'     => 'Blimbing, Kota Malang',
                'distance'     => '2 km',
                'rating'       => 4.9,
                'review_count' => 150,
                'ticket_price' => 'Rp 5.000',
                'open_hours'   => '08.00–17.00',
                'contact'      => '081234567890',
                'social_media' => '@jodipan_malang',
                'address'      => 'Kel. Jodipan, Blimbing, Kota Malang',
                'description'  => 'Kampung dengan rumah berwarna cerah dan mural artistik. Destinasi foto favorit di Malang.',
                'emoji'        => '🎨',
                'color'        => '#c0392b',
                'gradient'     => 'linear-gradient(135deg,#c0392b,#922b21)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Alun-Alun Kota Malang',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => '0.5 km',
                'rating'       => 4.8,
                'review_count' => 200,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Merdeka Selatan, Klojen, Kota Malang',
                'description'  => 'Pusat kota Malang yang selalu ramai. Terdapat pohon beringin tua dan berbagai penjual makanan.',
                'emoji'        => '🌿',
                'color'        => '#16a085',
                'gradient'     => 'linear-gradient(135deg,#16a085,#1abc9c)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Museum Brawijaya',
                'category'     => 'Wisata Budaya',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => '2.5 km',
                'rating'       => 4.7,
                'review_count' => 90,
                'ticket_price' => 'Rp 5.000',
                'open_hours'   => '08.00–16.00',
                'contact'      => '0341-362391',
                'social_media' => '@museumbrawijaya',
                'address'      => 'Jl. Ijen No.25A, Gading Kasri, Klojen, Kota Malang',
                'description'  => 'Museum militer yang menyimpan koleksi senjata dan kendaraan perang dari era kemerdekaan Indonesia.',
                'emoji'        => '🎖️',
                'color'        => '#2c3e50',
                'gradient'     => 'linear-gradient(135deg,#2c3e50,#34495e)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Pasar Besar Malang',
                'category'     => 'Kuliner & Belanja',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => '1.5 km',
                'rating'       => 4.6,
                'review_count' => 120,
                'ticket_price' => 'Gratis',
                'open_hours'   => '06.00–18.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Pasar Besar, Sukoharjo, Klojen, Kota Malang',
                'description'  => 'Pasar tradisional terbesar di Malang. Surga belanja oleh-oleh dan kuliner khas Malang.',
                'emoji'        => '🛒',
                'color'        => '#e67e22',
                'gradient'     => 'linear-gradient(135deg,#e67e22,#d35400)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Coban Rondo',
                'category'     => 'Wisata Alam',
                'location'     => 'Pujon, Kab. Malang',
                'distance'     => '30 km',
                'rating'       => 4.8,
                'review_count' => 175,
                'ticket_price' => 'Rp 20.000',
                'open_hours'   => '07.00–17.00',
                'contact'      => '082334455667',
                'social_media' => '@cobanrondo',
                'address'      => 'Desa Pandansari, Pujon, Kab. Malang',
                'description'  => 'Air terjun legendaris dengan ketinggian 84 meter di tengah hutan pinus yang sejuk.',
                'emoji'        => '🌊',
                'color'        => '#2980b9',
                'gradient'     => 'linear-gradient(135deg,#2980b9,#1a5276)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Malang Night Paradise',
                'category'     => 'Wisata Hiburan',
                'location'     => 'Lowokwaru, Kota Malang',
                'distance'     => '5 km',
                'rating'       => 4.7,
                'review_count' => 130,
                'ticket_price' => 'Rp 40.000',
                'open_hours'   => '16.00–23.00',
                'contact'      => '081233334444',
                'social_media' => '@malamnightparadise',
                'address'      => 'Jl. Terusan Sulfat, Blimbing, Kota Malang',
                'description'  => 'Taman hiburan malam dengan lampu warna-warni dan berbagai atraksi seru untuk keluarga.',
                'emoji'        => '✨',
                'color'        => '#8e44ad',
                'gradient'     => 'linear-gradient(135deg,#8e44ad,#6c3483)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Bakso President Malang',
                'category'     => 'Kuliner & Belanja',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => '2 km',
                'rating'       => 4.9,
                'review_count' => 300,
                'ticket_price' => 'Rp 15.000 – Rp 40.000',
                'open_hours'   => '08.00–21.00',
                'contact'      => '0341-364988',
                'social_media' => '@baksopresident',
                'address'      => 'Jl. Batanghari No.5, Rampalcelaket, Klojen, Kota Malang',
                'description'  => 'Bakso legendaris Malang yang sudah berdiri sejak 1977. Wajib dikunjungi pecinta kuliner.',
                'emoji'        => '🍜',
                'color'        => '#c0392b',
                'gradient'     => 'linear-gradient(135deg,#c0392b,#e74c3c)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Selecta',
                'category'     => 'Wisata Alam',
                'location'     => 'Batu, Kota Batu',
                'distance'     => '20 km',
                'rating'       => 4.6,
                'review_count' => 110,
                'ticket_price' => 'Rp 25.000',
                'open_hours'   => '07.00–17.00',
                'contact'      => '0341-591290',
                'social_media' => '@selectabatu',
                'address'      => 'Jl. Selecta No.1, Tulungrejo, Bumiaji, Kota Batu',
                'description'  => 'Taman wisata dengan kolam renang dan taman bunga yang indah di kawasan Kota Batu.',
                'emoji'        => '🌸',
                'color'        => '#e91e8c',
                'gradient'     => 'linear-gradient(135deg,#e91e8c,#c2185b)',
                'is_active'    => true,
            ],
        ];

        foreach ($destinations as $dest) {
            Destination::create($dest);
        }
    }
}
