<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        Destination::truncate();

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $destinations = [

            // ─── WISATA BUDAYA ────────────────────────────────────────────────
            [
                'name'         => 'Museum Brawijaya',
                'category'     => 'Wisata Budaya',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.7,
                'review_count' => 90,
                'ticket_price' => 'Rp 5.000 – Rp 10.000',
                'open_hours'   => '08.00–14.30 (Sen–Kam), 08.00–11.30 (Jum), 08.00–13.00 (Sab–Min)',
                'contact'      => 'N/A',
                'social_media' => '@museum_brawijaya',
                'address'      => 'Jl. Besar Ijen No.25A, Gading Kasri, Kec. Klojen, Kota Malang, Jawa Timur 65115',
                'description'  => 'Museum militer paling ikonik di Malang. Menyimpan koleksi senjata, kendaraan perang, dan Gerbong Maut yang bersejarah. Terletak di Jalan Ijen dengan arsitektur kolonial yang gagah.',
                'lat'          => -7.9637,
                'lng'          => 112.6196,
                'emoji'        => '🎖️',
                'color'        => '#2c3e50',
                'gradient'     => 'linear-gradient(135deg,#2c3e50,#34495e)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Museum Mpu Purwa',
                'category'     => 'Wisata Budaya',
                'location'     => 'Lowokwaru, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 55,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.30–15.00 (Selasa–Minggu)',
                'contact'      => 'N/A',
                'social_media' => '@museum_mpupurwa',
                'address'      => 'Jl. Soekarno-Hatta No.210 Blok B, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141',
                'description'  => 'Menyimpan koleksi benda cagar budaya berupa arca dan prasasti peninggalan kerajaan dari era Kanjuruhan hingga Majapahit. Gratis untuk dikunjungi.',
                'lat'          => -7.9306,
                'lng'          => 112.6192,
                'emoji'        => '🏺',
                'color'        => '#7a5830',
                'gradient'     => 'linear-gradient(135deg,#7a5830,#503820)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Museum Musik Indonesia',
                'category'     => 'Wisata Budaya',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.6,
                'review_count' => 70,
                'ticket_price' => 'Rp 5.000 – Rp 10.000',
                'open_hours'   => '10.00–17.00 (Selasa–Minggu)',
                'contact'      => 'N/A',
                'social_media' => '@museummusikindonesia',
                'address'      => 'Jl. Nusakambangan No.19, Kel. Kasin, Kec. Klojen, Kota Malang, Jawa Timur 65117',
                'description'  => 'Satu-satunya museum musik di Indonesia. Menyimpan ribuan koleksi piringan hitam, kaset, CD, hingga majalah musik dari dalam dan luar negeri. Surga bagi pecinta sejarah audio.',
                'lat'          => -7.9800,
                'lng'          => 112.6260,
                'emoji'        => '🎵',
                'color'        => '#8e44ad',
                'gradient'     => 'linear-gradient(135deg,#8e44ad,#6c3483)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Museum Motor Klasik',
                'category'     => 'Wisata Budaya',
                'location'     => 'Lowokwaru, Kota Malang',
                'distance'     => null,
                'rating'       => 4.4,
                'review_count' => 40,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.00–16.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Bunga Vinolia No.8b, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141',
                'description'  => 'Berlokasi di dalam kawasan SMK Panca Dharma. Menampilkan koleksi motor antik dan langka dari berbagai belahan dunia. Sangat menarik bagi penggemar otomotif retro.',
                'lat'          => -7.9290,
                'lng'          => 112.6180,
                'emoji'        => '🏍️',
                'color'        => '#2c3e50',
                'gradient'     => 'linear-gradient(135deg,#2c3e50,#95a5a6)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Museum Zoologi Frater Vianney',
                'category'     => 'Wisata Budaya',
                'location'     => 'Dau, Kab. Malang',
                'distance'     => null,
                'rating'       => 4.3,
                'review_count' => 30,
                'ticket_price' => 'Rp 20.000 – Rp 25.000',
                'open_hours'   => '08.00–14.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Raya Karangwidoro No.7, Desa Karangbesuki, Kec. Dau, Kabupaten Malang, Jawa Timur 65146',
                'description'  => 'Museum zoologi yang menyimpan koleksi spesimen hewan dari berbagai penjuru Indonesia. Cocok sebagai sarana edukasi bagi pelajar dan keluarga.',
                'lat'          => -7.9350,
                'lng'          => 112.5880,
                'emoji'        => '🦎',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#1e8449)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Heritage Kayutangan',
                'category'     => 'Wisata Budaya',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.9,
                'review_count' => 100,
                'ticket_price' => 'Rp 5.000',
                'open_hours'   => '06.00–22.00',
                'contact'      => 'N/A',
                'social_media' => 'https://heritage-kajoetangan.com/',
                'address'      => 'Jl. Raya Gempol-Malang, Kauman, Kec. Klojen, Kota Malang, Jawa Timur 65119',
                'description'  => 'Kawasan wisata budaya bersejarah di Klojen. Menyimpan jejak peradaban kolonial Belanda dengan deretan bangunan tua berarsitektur Eropa yang masih terawat hingga kini.',
                'lat'          => -7.9799,
                'lng'          => 112.6296,
                'emoji'        => '🏛️',
                'color'        => '#8b7355',
                'gradient'     => 'linear-gradient(135deg,#8b7355,#6b5233)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Budaya Polowijen',
                'category'     => 'Wisata Budaya',
                'location'     => 'Blimbing, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 45,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.00–17.00',
                'contact'      => 'N/A',
                'social_media' => '@kampungbudayapolowijen',
                'address'      => 'Jl. Cakalang, RT.3/RW.2, Polowijen, Kec. Blimbing, Kota Malang, Jawa Timur 65126',
                'description'  => 'Kampung budaya yang aktif digunakan untuk event kegiatan seni dan tradisi lokal Malang. Kaya akan pertunjukan tari dan kesenian daerah.',
                'lat'          => -7.9400,
                'lng'          => 112.6430,
                'emoji'        => '🎭',
                'color'        => '#e74c3c',
                'gradient'     => 'linear-gradient(135deg,#e74c3c,#c0392b)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Satrio Turonggo Jati',
                'category'     => 'Wisata Budaya',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.3,
                'review_count' => 28,
                'ticket_price' => 'Gratis',
                'open_hours'   => '10.00–21.00',
                'contact'      => '6285815177017',
                'social_media' => 'N/A',
                'address'      => 'Rampal Celaket, Kec. Klojen, Kota Malang, Jawa Timur',
                'description'  => 'Kampung seni yang menampilkan kesenian kuda lumping dan pertunjukan tradisional Jawa Timur. Tempat pelestarian budaya lokal yang autentik.',
                'lat'          => -7.9720,
                'lng'          => 112.6340,
                'emoji'        => '🐎',
                'color'        => '#d35400',
                'gradient'     => 'linear-gradient(135deg,#d35400,#e67e22)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Taman Krida Budaya Jawa Timur',
                'category'     => 'Wisata Budaya',
                'location'     => 'Lowokwaru, Kota Malang',
                'distance'     => null,
                'rating'       => 4.4,
                'review_count' => 50,
                'ticket_price' => 'Gratis (kecuali saat event)',
                'open_hours'   => '08.00–21.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Soekarno Hatta No.7, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65142',
                'description'  => 'Pusat kesenian dan budaya Jawa Timur di Malang. Sering menjadi venue pertunjukan seni tradisional, pameran budaya, dan festival daerah.',
                'lat'          => -7.9240,
                'lng'          => 112.6280,
                'emoji'        => '🎪',
                'color'        => '#16a085',
                'gradient'     => 'linear-gradient(135deg,#16a085,#1abc9c)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Koridor Kayutangan',
                'category'     => 'Wisata Budaya',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.7,
                'review_count' => 85,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Raya Gempol - Malang, Kauman, Kec. Klojen, Kota Malang, Jawa Timur 65119',
                'description'  => 'Kawasan heritage di jantung Kota Malang dengan bangunan bersejarah era kolonial. Cocok untuk jalan kaki malam hari sambil menikmati suasana kota tua.',
                'lat'          => -7.9800,
                'lng'          => 112.6300,
                'emoji'        => '🏙️',
                'color'        => '#8b7355',
                'gradient'     => 'linear-gradient(135deg,#8b7355,#a0856a)',
                'is_active'    => true,
            ],

            // ─── TAMAN KOTA ───────────────────────────────────────────────────
            [
                'name'         => 'Alun-Alun Kota Malang',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.8,
                'review_count' => 200,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Merdeka Selatan, Kel. Klojen, Kec. Klojen, Kota Malang, Jawa Timur 65119',
                'description'  => 'Ikon pusat kota yang dikelilingi pohon beringin tua berusia ratusan tahun. Pusat kegiatan masyarakat sejak zaman kolonial Belanda.',
                'lat'          => -7.9797,
                'lng'          => 112.6304,
                'emoji'        => '🌿',
                'color'        => '#16a085',
                'gradient'     => 'linear-gradient(135deg,#16a085,#1abc9c)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Alun-Alun Tugu Balaikota',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.7,
                'review_count' => 120,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Tugu, Kiduldalem, Kec. Klojen, Kota Malang, Jawa Timur 65111',
                'description'  => 'Taman ikonik di depan Balaikota Malang dengan tugu besar sebagai landmark utama. Populer untuk foto dan bersantai di sore hari.',
                'lat'          => -7.9762,
                'lng'          => 112.6323,
                'emoji'        => '🗽',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#1e8449)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Trunojoyo Park',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.9,
                'review_count' => 80,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Trunojoyo, Kelurahan Klojen, Kec. Klojen, Kota Malang, Jawa Timur 65111',
                'description'  => 'Taman terbuka yang berlokasi di dekat Stasiun Malang Kotabaru. Tempat berteduh dan bersantai yang nyaman di tengah kota.',
                'lat'          => -7.9758,
                'lng'          => 112.6275,
                'emoji'        => '🌳',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#1e8449)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Idjen Boulevard',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.8,
                'review_count' => 160,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam (Car Free Day: Minggu pagi)',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Ijen St, Oro-oro Dowo, Klojen, Malang City, East Java 65115',
                'description'  => 'Boulevar ikonik Kota Malang yang terkenal dengan pohon-pohon besar dan suasana asri. Setiap hari Minggu pagi jadi area Car Free Day yang ramai.',
                'lat'          => -7.9650,
                'lng'          => 112.6200,
                'emoji'        => '🌴',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#2ecc71)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Taman Singha Merjosari',
                'category'     => 'Taman Kota',
                'location'     => 'Lowokwaru, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 55,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Mertojoyo Selatan Blk. B No.20, Merjosari, Kec. Lowokwaru, Kota Malang, Jawa Timur 65144',
                'description'  => 'Taman kota dengan patung singa yang khas. Tempat olahraga pagi dan bersantai bagi warga Merjosari dan sekitarnya.',
                'lat'          => -7.9480,
                'lng'          => 112.6050,
                'emoji'        => '🦁',
                'color'        => '#f39c12',
                'gradient'     => 'linear-gradient(135deg,#f39c12,#e67e22)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Taman Cerdas Trunojoyo',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.6,
                'review_count' => 65,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Trunojoyo, Klojen, Kec. Klojen, Kota Malang, Jawa Timur 65111',
                'description'  => 'Taman edukatif dengan fasilitas belajar dan bermain untuk anak-anak. Dilengkapi perpustakaan mini dan area bermain yang aman.',
                'lat'          => -7.9760,
                'lng'          => 112.6280,
                'emoji'        => '📚',
                'color'        => '#3498db',
                'gradient'     => 'linear-gradient(135deg,#3498db,#2980b9)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Taman Merbabu',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 48,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Merbabu, Oro-oro Dowo, Kec. Klojen, Kota Malang, Jawa Timur 65119',
                'description'  => 'Taman kecil yang asri di kawasan Oro-oro Dowo. Cocok untuk bersantai sore hari di antara pepohonan rindang.',
                'lat'          => -7.9680,
                'lng'          => 112.6240,
                'emoji'        => '🌿',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#58d68d)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Taman Slamet',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.4,
                'review_count' => 35,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Taman Slamet St No.8, Gading Kasri, Klojen, Malang City, East Java 65115',
                'description'  => 'Taman hijau yang tenang di kawasan Gading Kasri. Favorit warga setempat untuk olahraga pagi dan jogging ringan.',
                'lat'          => -7.9600,
                'lng'          => 112.6160,
                'emoji'        => '🌸',
                'color'        => '#1abc9c',
                'gradient'     => 'linear-gradient(135deg,#1abc9c,#16a085)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Taman Kunang-Kunang',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 42,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jalan Jakarta Oro-oro Dowo, Penanggungan, Kec. Klojen, Kota Malang, Jawa Timur 65113',
                'description'  => 'Taman dengan nuansa unik yang menarik untuk dikunjungi malam hari. Area bermain anak yang nyaman dan aman.',
                'lat'          => -7.9700,
                'lng'          => 112.6320,
                'emoji'        => '✨',
                'color'        => '#f39c12',
                'gradient'     => 'linear-gradient(135deg,#f39c12,#f1c40f)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Taman Rekreasi Kota Malang',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.4,
                'review_count' => 38,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.00–16.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Mojopahit, Kiduldalem, Kec. Klojen, Kota Malang, Jawa Timur 65119',
                'description'  => 'Taman rekreasi keluarga di pusat kota dengan area hijau yang luas. Cocok untuk piknik dan bermain bersama anak.',
                'lat'          => -7.9820,
                'lng'          => 112.6290,
                'emoji'        => '🎪',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#82e0aa)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Hutan Kota Malabar Malang',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.6,
                'review_count' => 72,
                'ticket_price' => 'Gratis',
                'open_hours'   => '06.00–18.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Malabar, Oro-oro Dowo, Kec. Klojen, Kota Malang, Jawa Timur 65119',
                'description'  => 'Hutan kota yang rindang di tengah pemukiman Klojen. Tempat favorit jogging pagi dan olahraga ringan warga sekitar.',
                'lat'          => -7.9660,
                'lng'          => 112.6230,
                'emoji'        => '🌲',
                'color'        => '#196f3d',
                'gradient'     => 'linear-gradient(135deg,#196f3d,#27ae60)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Wana Wisata Perhutani Malang',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 60,
                'ticket_price' => 'Berbayar',
                'open_hours'   => 'Senin–Jumat 08.00–16.00, Sabtu–Minggu 24 Jam',
                'contact'      => '6281235419696',
                'social_media' => 'N/A',
                'address'      => 'Jl. Dr. Cipto No.14a, Rampal Celaket, Kec. Klojen, Kota Malang, Jawa Timur 65111',
                'description'  => 'Area hutan wisata milik Perhutani dengan suasana alam yang asri di dalam kota. Cocok untuk jalan santai dan menikmati udara segar.',
                'lat'          => -7.9730,
                'lng'          => 112.6350,
                'emoji'        => '🌿',
                'color'        => '#196f3d',
                'gradient'     => 'linear-gradient(135deg,#196f3d,#1e8449)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Taman Raung',
                'category'     => 'Taman Kota',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.3,
                'review_count' => 25,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Ijen St No.76, Oro-oro Dowo, Klojen, Malang City, East Java 65112',
                'description'  => 'Taman di lingkungan tempat tinggal kawasan Ijen yang asri. Tempat bersantai ringan bagi warga sekitar.',
                'lat'          => -7.9655,
                'lng'          => 112.6205,
                'emoji'        => '🍃',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#a9dfbf)',
                'is_active'    => true,
            ],

            // ─── WISATA EDUKASI ───────────────────────────────────────────────
            [
                'name'         => 'Perpustakaan Kota Malang',
                'category'     => 'Wisata Edukasi',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 50,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.00–15.30 (Sen–Kam), 08.00–14.30 (Jumat)',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Ijen No.30A, Oro-oro Dowo, Kec. Klojen, Kota Malang, Jawa Timur 65115',
                'description'  => 'Pusat literasi modern yang nyaman dengan koleksi buku lengkap. Memiliki area baca anak, ruang diskusi, dan fasilitas internet gratis tepat di samping Taman Trunojoyo.',
                'lat'          => -7.9644,
                'lng'          => 112.6198,
                'emoji'        => '📖',
                'color'        => '#2980b9',
                'gradient'     => 'linear-gradient(135deg,#2980b9,#1a5276)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Brawijaya Edu Park',
                'category'     => 'Wisata Edukasi',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 75,
                'ticket_price' => 'Rp 20.000',
                'open_hours'   => '08.00–16.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Kahuripan No.1, Kel. Klojen, Kec. Klojen, Kota Malang, Jawa Timur 65119',
                'description'  => 'Taman rekreasi keluarga legendaris (dahulu Senaputra). Kini berfungsi sebagai pusat edukasi dan hiburan dengan kolam renang, area bermain, serta panggung seni budaya.',
                'lat'          => -7.9790,
                'lng'          => 112.6310,
                'emoji'        => '🎢',
                'color'        => '#e74c3c',
                'gradient'     => 'linear-gradient(135deg,#e74c3c,#c0392b)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Warna-Warni Jodipan',
                'category'     => 'Wisata Edukasi',
                'location'     => 'Blimbing, Kota Malang',
                'distance'     => null,
                'rating'       => 4.9,
                'review_count' => 150,
                'ticket_price' => 'Rp 5.000',
                'open_hours'   => '07.00–17.00',
                'contact'      => '081234567890',
                'social_media' => '@jodipan_malang',
                'address'      => 'Jl. Ir. H. Juanda No.RT.7, RT.09/RW.2, Jodipan, Kec. Blimbing, Kota Malang, Jawa Timur 65127',
                'description'  => 'Kampung dengan rumah-rumah berwarna cerah dan mural artistik di sepanjang tepi Sungai Brantas. Destinasi foto paling populer di Malang yang menginspirasi kreativitas.',
                'lat'          => -7.9720,
                'lng'          => 112.6450,
                'emoji'        => '🎨',
                'color'        => '#c0392b',
                'gradient'     => 'linear-gradient(135deg,#c0392b,#922b21)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Tridi',
                'category'     => 'Wisata Edukasi',
                'location'     => 'Blimbing, Kota Malang',
                'distance'     => null,
                'rating'       => 4.6,
                'review_count' => 80,
                'ticket_price' => 'Rp 5.000',
                'open_hours'   => '07.00–18.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Temenggungan Ledok, Kel. Kesatrian, Kec. Blimbing, Kota Malang, Jawa Timur',
                'description'  => 'Kampung dengan mural 3D yang memukau di seberang Kampung Warna-Warni. Spot foto unik dengan ilusi optik yang kreatif dan instagramable.',
                'lat'          => -7.9715,
                'lng'          => 112.6440,
                'emoji'        => '🖼️',
                'color'        => '#9b59b6',
                'gradient'     => 'linear-gradient(135deg,#9b59b6,#8e44ad)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Sanan Tempe',
                'category'     => 'Wisata Edukasi',
                'location'     => 'Blimbing, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 65,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.00–20.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Sanan No.35, Kel. Purwantoro, Kec. Blimbing, Kota Malang, Jawa Timur 65122',
                'description'  => 'Sentra produksi tempe terbesar di Malang. Wisatawan bisa melihat langsung proses pembuatan tempe dan membeli berbagai olahan tempe khas Sanan.',
                'lat'          => -7.9500,
                'lng'          => 112.6510,
                'emoji'        => '🫘',
                'color'        => '#d4ac0d',
                'gradient'     => 'linear-gradient(135deg,#d4ac0d,#b7950b)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Keramik Dinoyo',
                'category'     => 'Wisata Edukasi',
                'location'     => 'Lowokwaru, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 58,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.00–16.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. MT Haryono 9 No.336, Dinoyo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65144',
                'description'  => 'Sentra kerajinan keramik tradisional Malang. Pengunjung bisa melihat dan mencoba membuat keramik langsung dari pengrajin berpengalaman.',
                'lat'          => -7.9420,
                'lng'          => 112.6090,
                'emoji'        => '🏺',
                'color'        => '#e67e22',
                'gradient'     => 'linear-gradient(135deg,#e67e22,#ca6f1e)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Gerabah Penanggungan',
                'category'     => 'Wisata Edukasi',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.3,
                'review_count' => 32,
                'ticket_price' => 'Rp 5.000',
                'open_hours'   => '08.00–16.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Mayjen Panjaitan Dalam No.Gg. 18C, Penanggungan, Kec. Klojen, Kota Malang, Jawa Timur 65113',
                'description'  => 'Kampung pengrajin gerabah tradisional di Penanggungan. Cocok untuk wisata edukasi dan mengenal seni kerajinan tanah liat khas Malang.',
                'lat'          => -7.9740,
                'lng'          => 112.6360,
                'emoji'        => '🪴',
                'color'        => '#a0522d',
                'gradient'     => 'linear-gradient(135deg,#a0522d,#8b4513)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung 1000 Topeng',
                'category'     => 'Wisata Edukasi',
                'location'     => 'Kedungkandang, Kota Malang',
                'distance'     => null,
                'rating'       => 4.4,
                'review_count' => 45,
                'ticket_price' => 'Rp 5.000',
                'open_hours'   => '07.00–17.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Tlogowaru, Kec. Kedungkandang, Kota Malang, Jawa Timur 65133',
                'description'  => 'Kampung pengrajin topeng kayu tradisional khas Malangan. Tempat pelestarian kesenian topeng yang sudah diwariskan turun-temurun.',
                'lat'          => -8.0060,
                'lng'          => 112.6620,
                'emoji'        => '🎭',
                'color'        => '#e74c3c',
                'gradient'     => 'linear-gradient(135deg,#e74c3c,#922b21)',
                'is_active'    => true,
            ],

            // ─── WISATA HIBURAN ───────────────────────────────────────────────
            [
                'name'         => 'Taman Rekreasi Tlogomas',
                'category'     => 'Wisata Hiburan',
                'location'     => 'Lowokwaru, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 85,
                'ticket_price' => 'Rp 25.000',
                'open_hours'   => 'Jumat–Rabu 07.00–16.30',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Baiduri Pandan No.17, Tlogomas, Kec. Lowokwaru, Kota Malang, Jawa Timur 65144',
                'description'  => 'Taman untuk keluarga dengan kolam renang outdoor, seluncuran air, dan patung dinosaurus. Favorit keluarga untuk liburan akhir pekan.',
                'lat'          => -7.9390,
                'lng'          => 112.5970,
                'emoji'        => '🦕',
                'color'        => '#16a085',
                'gradient'     => 'linear-gradient(135deg,#16a085,#1abc9c)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Trans Studio Mini Malang',
                'category'     => 'Wisata Hiburan',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.8,
                'review_count' => 120,
                'ticket_price' => 'Berbayar',
                'open_hours'   => '10.00–22.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Transmart MX Malang, Jl. Veteran No.8 lantai F4, Penanggungan, Kec. Klojen, Kota Malang, Jawa Timur 65113',
                'description'  => 'Wahana hiburan indoor di dalam mall. Menawarkan berbagai permainan seru untuk keluarga dan anak-anak. Cocok untuk liburan saat cuaca hujan.',
                'lat'          => -7.9750,
                'lng'          => 112.6360,
                'emoji'        => '🎡',
                'color'        => '#8e44ad',
                'gradient'     => 'linear-gradient(135deg,#8e44ad,#6c3483)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Istana Dieng Club House',
                'category'     => 'Wisata Hiburan',
                'location'     => 'Sukun, Kota Malang',
                'distance'     => null,
                'rating'       => 4.4,
                'review_count' => 48,
                'ticket_price' => 'Rp 50.000',
                'open_hours'   => '05.30–20.30',
                'contact'      => '(0341)561222',
                'social_media' => 'N/A',
                'address'      => 'Perumahan Istana Dieng Jalan Istana Dieng, Raya III, Bandulan, Kec. Sukun, Kota Malang, Jawa Timur 65146',
                'description'  => 'Fasilitas olahraga dan rekreasi lengkap di kawasan perumahan Istana Dieng. Terdapat kolam renang, lapangan tenis, dan area bermain anak.',
                'lat'          => -7.9890,
                'lng'          => 112.6040,
                'emoji'        => '🏊',
                'color'        => '#3498db',
                'gradient'     => 'linear-gradient(135deg,#3498db,#2980b9)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Eco Club Citra Garden',
                'category'     => 'Wisata Hiburan',
                'location'     => 'Kedungkandang, Kota Malang',
                'distance'     => null,
                'rating'       => 4.3,
                'review_count' => 35,
                'ticket_price' => 'Berbayar',
                'open_hours'   => '08.00–17.00',
                'contact'      => 'N/A',
                'social_media' => '@ecoclub.citragardencitymalang',
                'address'      => 'Buring, Kec. Kedungkandang, Kota Malang, Jawa Timur 65136',
                'description'  => 'Fasilitas olahraga dan rekreasi di kawasan perumahan Citra Garden. Dilengkapi kolam renang, lapangan futsal, dan taman bermain anak.',
                'lat'          => -8.0030,
                'lng'          => 112.6580,
                'emoji'        => '⛳',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#2ecc71)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Wisata Aeng Hamid Rusdi',
                'category'     => 'Wisata Hiburan',
                'location'     => 'Kedungkandang, Kota Malang',
                'distance'     => null,
                'rating'       => 4.3,
                'review_count' => 30,
                'ticket_price' => 'Rp 25.000',
                'open_hours'   => 'Sabtu–Kamis 24 Jam, Jumat 13.00–00.00',
                'contact'      => '6281252084186',
                'social_media' => 'N/A',
                'address'      => 'Jl. Kalisari No.60, Wonokoyo, Kec. Kedungkandang, Kota Malang, Jawa Timur 65135',
                'description'  => 'Wisata alam dengan kolam renang dan area piknik yang asri. Cocok untuk keluarga yang ingin bersantai di alam terbuka tanpa perlu jauh keluar kota.',
                'lat'          => -8.0100,
                'lng'          => 112.6730,
                'emoji'        => '🏕️',
                'color'        => '#2ecc71',
                'gradient'     => 'linear-gradient(135deg,#2ecc71,#27ae60)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Lampion Wangi',
                'category'     => 'Wisata Hiburan',
                'location'     => 'Blimbing, Kota Malang',
                'distance'     => null,
                'rating'       => 4.6,
                'review_count' => 70,
                'ticket_price' => 'Rp 75.000 – Rp 100.000',
                'open_hours'   => '08.00–16.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Ir. H. Juanda 9a No.23, Jodipan, Kec. Blimbing, Kota Malang, Jawa Timur 65126',
                'description'  => 'Kampung dengan dekorasi lampion warna-warni yang memukau. Spot foto unik dan instagramable, terutama saat sore dan malam hari.',
                'lat'          => -7.9725,
                'lng'          => 112.6455,
                'emoji'        => '🏮',
                'color'        => '#e74c3c',
                'gradient'     => 'linear-gradient(135deg,#e74c3c,#f39c12)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Bamboo Mewek Park',
                'category'     => 'Wisata Hiburan',
                'location'     => 'Lowokwaru, Kota Malang',
                'distance'     => null,
                'rating'       => 4.4,
                'review_count' => 40,
                'ticket_price' => 'Gratis',
                'open_hours'   => '07.00–17.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Ikan Tombro Barat, Tunjungsekar, Kec. Lowokwaru, Kota Malang, Jawa Timur 65142',
                'description'  => 'Taman bambu yang unik dengan fasilitas bermain anak dan area bersantai keluarga. Nuansa alam yang menyegarkan di tengah lingkungan perumahan.',
                'lat'          => -7.9210,
                'lng'          => 112.6300,
                'emoji'        => '🎋',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#a9dfbf)',
                'is_active'    => true,
            ],

            // ─── KULINER LEGENDARIS ───────────────────────────────────────────
            [
                'name'         => 'Bakso President Malang',
                'category'     => 'Kuliner Legendaris',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.9,
                'review_count' => 300,
                'ticket_price' => 'Rp 15.000 – Rp 40.000',
                'open_hours'   => '08.00–21.00',
                'contact'      => '0341-364988',
                'social_media' => '@baksopresident',
                'address'      => 'Jl. Batanghari No.5, Rampalcelaket, Klojen, Kota Malang',
                'description'  => 'Bakso legendaris Malang yang sudah berdiri sejak 1977. Wajib dikunjungi pecinta kuliner. Rasa autentik yang tidak berubah selama puluhan tahun.',
                'lat'          => -7.9730,
                'lng'          => 112.6350,
                'emoji'        => '🍜',
                'color'        => '#c0392b',
                'gradient'     => 'linear-gradient(135deg,#c0392b,#e74c3c)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Pasar Bunga & Burung Splendid',
                'category'     => 'Kuliner Legendaris',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 70,
                'ticket_price' => 'Gratis',
                'open_hours'   => '07.00–17.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Brawijaya, Kauman, Kec. Klojen, Kota Malang, Jawa Timur 65119',
                'description'  => 'Pasar ikonik Malang yang menjual aneka bunga segar, tanaman hias, dan burung. Surga bagi pecinta tanaman dan binatang peliharaan.',
                'lat'          => -7.9765,
                'lng'          => 112.6275,
                'emoji'        => '🌺',
                'color'        => '#e91e8c',
                'gradient'     => 'linear-gradient(135deg,#e91e8c,#c2185b)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Night Market Pasar Besar',
                'category'     => 'Kuliner Legendaris',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.6,
                'review_count' => 95,
                'ticket_price' => 'Gratis (harga makanan varies)',
                'open_hours'   => '18.00–22.30',
                'contact'      => '6287866170365',
                'social_media' => 'N/A',
                'address'      => 'Jl. Kyai Tamin No.15-49, Sukoharjo, Kec. Klojen, Kota Malang, Jawa Timur 65118',
                'description'  => 'Pasar malam legendaris di Kota Malang dengan ratusan pedagang kuliner. Surga jajanan malam yang wajib dikunjungi untuk merasakan kuliner khas Malang.',
                'lat'          => -7.9840,
                'lng'          => 112.6340,
                'emoji'        => '🌙',
                'color'        => '#2c3e50',
                'gradient'     => 'linear-gradient(135deg,#2c3e50,#f39c12)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Pasar Klojen',
                'category'     => 'Kuliner Legendaris',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.7,
                'review_count' => 60,
                'ticket_price' => 'Gratis',
                'open_hours'   => '06.00–16.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Cokroaminoto, Klojen, Kec. Klojen, Kota Malang, Jawa Timur 65111',
                'description'  => 'Pasar tradisional tertua di Klojen yang menjual berbagai kebutuhan sehari-hari dan kuliner khas Malang. Pengalaman belanja yang autentik dan terjangkau.',
                'lat'          => -7.9790,
                'lng'          => 112.6280,
                'emoji'        => '🛒',
                'color'        => '#e67e22',
                'gradient'     => 'linear-gradient(135deg,#e67e22,#ca6f1e)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Pasar Oro-Oro Dowo',
                'category'     => 'Kuliner Legendaris',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 40,
                'ticket_price' => 'Gratis',
                'open_hours'   => '05.00–17.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Guntur No.20, Oro-oro Dowo, Kec. Klojen, Kota Malang, Jawa Timur 65112',
                'description'  => 'Pasar tradisional dengan berbagai kebutuhan pangan segar dan kuliner khas Malang. Suasana autentik yang cocok untuk mencicipi cita rasa asli Jawa Timur.',
                'lat'          => -7.9670,
                'lng'          => 112.6220,
                'emoji'        => '🥘',
                'color'        => '#d35400',
                'gradient'     => 'linear-gradient(135deg,#d35400,#e67e22)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Pasar Besar Malang',
                'category'     => 'Kuliner Legendaris',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.6,
                'review_count' => 120,
                'ticket_price' => 'Gratis',
                'open_hours'   => '06.00–18.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Pasar Besar, Sukoharjo, Klojen, Kota Malang',
                'description'  => 'Pasar tradisional terbesar di Malang. Surga belanja oleh-oleh khas Malang dan kuliner yang beragam. Selalu ramai dan hidup sepanjang hari.',
                'lat'          => -7.9838,
                'lng'          => 112.6342,
                'emoji'        => '🏪',
                'color'        => '#e67e22',
                'gradient'     => 'linear-gradient(135deg,#e67e22,#d35400)',
                'is_active'    => true,
            ],

            // ─── WISATA ALAM ──────────────────────────────────────────────────
            [
                'name'         => 'Kampung Putih',
                'category'     => 'Wisata Alam',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.4,
                'review_count' => 42,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.00–16.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Jaksa Agung Suprapto, Klojen, Kec. Klojen, Kota Malang, Jawa Timur 65112',
                'description'  => 'Kampung tematik bernuansa putih bersih. Semua bangunan dicat putih menciptakan estetika unik yang instagramable di tengah kota.',
                'lat'          => -7.9760,
                'lng'          => 112.6300,
                'emoji'        => '🤍',
                'color'        => '#95a5a6',
                'gradient'     => 'linear-gradient(135deg,#95a5a6,#bdc3c7)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Keramat',
                'category'     => 'Wisata Alam',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.3,
                'review_count' => 28,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.00–16.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Bali No.9, Kasin, Klojen, Malang City, East Java 65117',
                'description'  => 'Kampung tematik dengan suasana yang tenang dan asri. Dikenal dengan keunikan bangunan dan hijaunya tanaman di sepanjang gang.',
                'lat'          => -7.9810,
                'lng'          => 112.6260,
                'emoji'        => '🌺',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#58d68d)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Biru Arema',
                'category'     => 'Wisata Alam',
                'location'     => 'Klojen, Kota Malang',
                'distance'     => null,
                'rating'       => 4.5,
                'review_count' => 65,
                'ticket_price' => 'Rp 3.000 – Rp 5.000',
                'open_hours'   => '07.00–18.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Kiduldalem, Kec. Klojen, Kota Malang, Jawa Timur 65119',
                'description'  => 'Kampung bernuansa biru identik dengan warna kebanggaan Arema Malang. Mural dan ornamen biru menghiasi setiap sudut gang yang instagramable.',
                'lat'          => -7.9830,
                'lng'          => 112.6330,
                'emoji'        => '💙',
                'color'        => '#2980b9',
                'gradient'     => 'linear-gradient(135deg,#2980b9,#3498db)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Rolakku Indah',
                'category'     => 'Wisata Alam',
                'location'     => 'Kedungkandang, Kota Malang',
                'distance'     => null,
                'rating'       => 4.3,
                'review_count' => 30,
                'ticket_price' => 'Gratis',
                'open_hours'   => '07.00–18.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Jl. Ki Ageng Gribig No.499, Kedungkandang, Kec. Kedungkandang, Kota Malang, Jawa Timur 65137',
                'description'  => 'Kampung tematik yang indah di tepi sungai. Dihiasi dengan tanaman dan dekorasi warna-warni yang menciptakan suasana asri dan segar.',
                'lat'          => -7.9980,
                'lng'          => 112.6650,
                'emoji'        => '🌊',
                'color'        => '#3498db',
                'gradient'     => 'linear-gradient(135deg,#3498db,#27ae60)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Koeboeran Londo',
                'category'     => 'Wisata Alam',
                'location'     => 'Sukun, Kota Malang',
                'distance'     => null,
                'rating'       => 4.2,
                'review_count' => 22,
                'ticket_price' => 'Gratis',
                'open_hours'   => '07.00–16.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Kec. Sukun, Kota Malang',
                'description'  => 'Kampung bersejarah era kolonial yang masih mempertahankan nuansa Belanda kuno. Unik dengan arsitektur dan tata kota peninggalan zaman Londo.',
                'lat'          => -7.9950,
                'lng'          => 112.6100,
                'emoji'        => '🏘️',
                'color'        => '#7f8c8d',
                'gradient'     => 'linear-gradient(135deg,#7f8c8d,#95a5a6)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Terapi Hijau',
                'category'     => 'Wisata Alam',
                'location'     => 'Sukun, Kota Malang',
                'distance'     => null,
                'rating'       => 4.4,
                'review_count' => 38,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.00–17.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Gg. 2C No.11, Sukun, Kec. Sukun, Kota Malang, Jawa Timur 65147',
                'description'  => 'Kampung hijau dengan konsep terapi alam. Dipenuhi tanaman obat dan tanaman hias yang menyegarkan. Udara segar dan nuansa alam membuat betah berlama-lama.',
                'lat'          => -7.9940,
                'lng'          => 112.6080,
                'emoji'        => '🌱',
                'color'        => '#196f3d',
                'gradient'     => 'linear-gradient(135deg,#196f3d,#27ae60)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Nila Slilir',
                'category'     => 'Wisata Alam',
                'location'     => 'Sukun, Kota Malang',
                'distance'     => null,
                'rating'       => 4.3,
                'review_count' => 25,
                'ticket_price' => 'Gratis',
                'open_hours'   => '08.00–17.00',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Belakang PP. Hidayatul Mubtadiin, Jl. Pelabuhan Tanjung Priok No.93, Bakalankrajan, Sukun, Kota Malang',
                'description'  => 'Kampung tematik di tepi sungai dengan tanaman nila yang menghijau. Suasana pedesaan yang menenangkan di tengah lingkungan urban Kota Malang.',
                'lat'          => -8.0010,
                'lng'          => 112.6120,
                'emoji'        => '💧',
                'color'        => '#2980b9',
                'gradient'     => 'linear-gradient(135deg,#2980b9,#27ae60)',
                'is_active'    => true,
            ],
            [
                'name'         => 'Kampung Karangbesuki',
                'category'     => 'Wisata Alam',
                'location'     => 'Sukun, Kota Malang',
                'distance'     => null,
                'rating'       => 4.2,
                'review_count' => 20,
                'ticket_price' => 'Gratis',
                'open_hours'   => '24 Jam (Area Desa)',
                'contact'      => 'N/A',
                'social_media' => 'N/A',
                'address'      => 'Kec. Sukun, Kota Malang, Jawa Timur',
                'description'  => 'Kawasan desa yang asri dan hijau di Sukun. Suasana pedesaan yang tenang jauh dari keramaian kota, cocok untuk relaksasi dan menikmati alam.',
                'lat'          => -7.9930,
                'lng'          => 112.6060,
                'emoji'        => '🌾',
                'color'        => '#27ae60',
                'gradient'     => 'linear-gradient(135deg,#27ae60,#a9dfbf)',
                'is_active'    => true,
            ],
        ];

        foreach ($destinations as $dest) {
            Destination::create($dest);
        }
    }
}